### ISSUE TITLE
Use lastSuccessfulBuild/lastUnsuccessfulBuild for level up calculation

### ISSUE THREAD

**Issue by jonnyarnold** [reevoo/ci_game#1]
On the JSON for the build ([http://ci/job/world/api/json?pretty=true](http://ci/job/world/api/json?pretty=true)) we can get the `lastSuccessfulBuild` and `lastUnsuccessfulBuild` numbers. We could use these to calculate the number of consecutive successful builds, rather than having to perform a JSON request for each build.

`numConsecutiveSuccessfulBuilds = lastCompletedBuild - lastUnsuccessfulBuild`
(note that this can be < 0)

**Comment by errm** [comment]
Good spot
